# AUL Configuration File
enabled = true
respectGitignoreFile = true
sizeOfABigFile = 100
autoValidateOnStartup = true
currentHashAlgorithm = "sha-256"
hash_exceptions = ["aul/disable/*", "aul/backup/*", "aul/hash_tree.aul", "core.aul", ".git/*"]
autoBackupBeforeUpdate = true
howToHandleLogs = "clear"
howToHandleMissingHashTreeFiles = "disable"
autoUpdateChannel = "stable"
prioritizeOnlineConfig = false

[Updates.Stable]
repo = "https://github.com/KRWCLASSIC/alutesting"
rawRepoCoreAul = "https://raw.githubusercontent.com/KRWCLASSIC/alutesting/refs/heads/main/core.aul"

[Updates.Nightly]
repo = "https://github.com/KRWCLASSIC/alutesting"
rawRepoCoreAul = "https://raw.githubusercontent.com/KRWCLASSIC/alutesting/refs/heads/main/core.aul"

[Updates.Custom]
repo = "test value for updating config"
rawRepoCoreAul = ""
